# Generated by Django 4.1.1 on 2022-10-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('player_surname', models.CharField(max_length=30, verbose_name='Apellido')),
                ('image_photoplayer', models.ImageField(upload_to='media', verbose_name='Foto del jugador')),
                ('player_datebirth', models.DateTimeField(verbose_name='Fecha De Nacimiento')),
                ('player_position', models.CharField(max_length=50, verbose_name='Posición en la que juega')),
                ('player_numshirt', models.CharField(max_length=2, verbose_name='Número de camiseta')),
                ('player_headline', models.CharField(max_length=30, verbose_name='¿Es Titular?')),
                ('player_team', models.CharField(max_length=30, verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'jugador',
                'db_table': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, verbose_name='Nombre del Equipo')),
                ('image_flag', models.ImageField(upload_to='media', verbose_name='Imagen Bandera')),
                ('image_shield', models.ImageField(upload_to='media', verbose_name='Escudo del Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'equipo',
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('position_description', models.CharField(max_length=50, verbose_name='Descripción')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEduor.player')),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'positions',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEduor.team'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('coach_surname', models.CharField(max_length=30, verbose_name='Apellido')),
                ('coach_datebirth', models.DateTimeField(verbose_name='Fecha De Nacimiento')),
                ('coach_nacionality', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('coach_rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEduor.team')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'técnico',
                'db_table': 'Coach',
            },
        ),
    ]
